---
aws_region: us-east-2
aws_profile: root-user

elastic_ip: 18.217.163.226

### don't change
vpc_name: "jenkins-{{ aws_region }}-vpc"
vpc_cidr: 10.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}c"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: https
    description: "Open HTTPS port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 443
  - name: http
    description: "Open HTTP port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80

ec2_instance_type: t2.micro
ec2_image: ami-0e82959d4ed12de3f
### don't change

r53_zone: achirashah.com
r53_record: jenkins-server.achirashah.com

keypair: "mykeypair"
ansible_ssh_private_key_file: ~/.ssh/mykeypair

# this line may not be needed, it is required to have in my system
ansible_python_interpreter: /usr/bin/python3
interpreter_python: /usr/bin/python3