---
#check connectivity to host server  
# - name: Check connectivity to host server
#   hosts: local
#   tasks:
#     - name: Ping test
#       ping:

#Main YML to execute all roles and playbook
- name: "aws infrastructure"
  hosts: localhost
  gather_facts: false

  roles:
    - {role: 'common', tags: 'create'}

    - {role: 'terminate', tags: 'delete'}

#   - {role: 'jenkins', tags: 'jenkins'}

- name: "Boran EC2 jenkins setup"
  hosts: boran-ec2
  gather_facts: false
  remote_user: ubuntu
  become: yes
  roles:
    - {role: 'jenkins', tags: 'boran-jenkins'}

# add your own values to hosts and add your play
- name: "Achira EC2 jenkins setup"
  hosts: achira-ec2
  gather_facts: false
  remote_user: ubuntu
  become: yes
  roles:
    - {role: 'jenkins', tags: 'achira-jenkins'}

# ec2 instance create
- name: "Apurva EC2 jenkins setup"
  hosts: apurva-ec2
  gather_facts: false
  remote_user: ubuntu
  become: yes
  roles:
    - {role: 'jenkins', tags: 'apurva-jenkins'}