---
- name: Get vpc id
  ec2_vpc_net_info:
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    filters:
      "tag:Name": "{{vpc_name}}"
  register: vpc_info

- name: Gather EC2 info
  ec2_instance_info:
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    filters:
      "tag:app" : "{{ app }}"
      vpc-id : "{{vpc_info.vpcs[0].vpc_id}}" 
  when: vpc_info.vpcs|length != 0  
  register: ec2_info

- name: Terminate EC2 instance
  ec2:
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    state: 'absent'
    wait: yes
    instance_ids: "{{ item.instance_id }}"
  when: vpc_info.vpcs|length != 0
  with_items: "{{ ec2_info.instances }}"

- name: Disassociate the elastic IP from the terminated instance
  ec2_eip:
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    device_id: "{{ item.instance_id }}"
    ip: "{{ elastic_ip }}"
    state: absent
  with_items: "{{ ec2_info.instances }}"